[project]
name = "ai-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vvadr", email = "abdulazizyusupaliev009@example.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.6",
]

[project.scripts]
ai-ml = "ai_ml:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
]
